### ISSUE TITLE
Anndata2ri install fail

### ISSUE THREAD

**Issue by heeroena** [theislab/anndata2ri#23] opened 2019-08-16 09:20 UTC
dear Theis lab,
I have been having issues installing the anndata2ri packages on anaconda using your git command. I hope to get some guidance as to how I could solve the issue. the issue seems to be related to rpy2 which i have already installed (version 2.9.5)
I get the following error:

```
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\name\AppData\Local\Temp\pip-install-o14d0uw2\rpy2\
  ----------------------------------------
ERROR: Command "'C:\ProgramData\Anaconda3\python.exe' 'C:\ProgramData\Anaconda3\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\name\AppData\Local\Temp\pip-build-env-3dvsy3kv\normal' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- tzlocal anndata 'pytest; extra == "test"' 'rpy2 >= 3.0.1' 'pytest-faulthandler; extra == "test"'" failed with error code 1 in None
````

regards

L

**Comment by flying-sheep** [comment] 2019-08-16 09:43
Hi! Sadly your error is profoundly unhelpful, there’s nothing in there that I can use to understand what went wrong. Do you have more output?

Before replying, please also familiarize yourself with [Markdown](https://guides.github.com/features/mastering-markdown/), especially how to create code blocks.

**Comment by heeroena** [comment] 2019-08-16 09:56
Apologies. this is the complete output i get from the anaconda prompt after running 
pip install git+https://github.com/flying-sheep/anndata2ri.git.

[error.txt](https://github.com/theislab/anndata2ri/files/3509037/error.txt)
I hope this is more helpful.

kind regards,

EL

**Comment by flying-sheep** [comment] 2019-08-16 10:58
Yes, this is an error installing rpy2 and therefore a duplicate of #21. You can find more people having that problem [here](https://stackoverflow.com/questions/14882477/rpy2-install-on-windows-7), the error [reported in the rpy2 repo here](https://bitbucket.org/rpy2/rpy2/issues/569/error-when-installing-pip-install-rpy2).

**Closed by flying-sheep** 2019-08-16 10:58 UTC
