### ISSUE TITLE
RStudio crash when importing anndata2ri

### ISSUE THREAD

**Issue by JLiLab** [theislab/anndata2ri#45] opened 2020-05-22 19:06 UTC
While other python packages work fine, importing anndata2r1 crashes RStudio. Any suggests how to fix this problem? Here is the session info: 

R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Seurat_3.1.5    ggplot2_3.3.0   reticulate_1.15

loaded via a namespace (and not attached):
 [1] httr_1.4.1         tidyr_1.1.0        jsonlite_1.6.1     viridisLite_0.3.0  splines_4.0.0      leiden_0.3.3      
 [7] assertthat_0.2.1   ggrepel_0.8.2      sessioninfo_1.1.1  globals_0.12.5     pillar_1.4.4       lattice_0.20-41   
[13] glue_1.4.1         digest_0.6.25      RColorBrewer_1.1-2 colorspace_1.4-1   cowplot_1.0.0      htmltools_0.4.0   
[19] Matrix_1.2-18      plyr_1.8.6         pkgconfig_2.0.3    tsne_0.1-3         listenv_0.8.0      purrr_0.3.4       
[25] patchwork_1.0.0    scales_1.1.1       RANN_2.6.1         Rtsne_0.15         tibble_3.0.1       ellipsis_0.3.1    
[31] withr_2.2.0        ROCR_1.0-11        pbapply_1.4-2      lazyeval_0.2.2     cli_2.0.2          survival_3.1-12   
[37] magrittr_1.5       crayon_1.3.4       future_1.17.0      fansi_0.4.1        nlme_3.1-147       MASS_7.3-51.5     
[43] ica_1.0-2          tools_4.0.0        fitdistrplus_1.1-1 data.table_1.12.8  lifecycle_0.2.0    stringr_1.4.0     
[49] plotly_4.9.2.1     munsell_0.5.0      cluster_2.1.0      irlba_2.3.3        compiler_4.0.0     rsvd_1.0.3        
[55] rlang_0.4.6        grid_4.0.0         ggridges_0.5.2     rstudioapi_0.11    RcppAnnoy_0.0.16   htmlwidgets_1.5.1 
[61] igraph_1.2.5       gtable_0.3.0       codetools_0.2-16   reshape2_1.4.4     R6_2.4.1           gridExtra_2.3     
[67] zoo_1.8-8          knitr_1.28         dplyr_0.8.5        uwot_0.1.8         future.apply_1.5.0 KernSmooth_2.23-16
[73] ape_5.3            stringi_1.4.6      parallel_4.0.0     Rcpp_1.0.4.6       vctrs_0.3.0        sctransform_0.2.1 
[79] png_0.1-7          tidyselect_1.1.0   xfun_0.14          lmtest_0.9-37

**Comment by flying-sheep** [comment] 2020-05-24 14:29
anndata2ri is a python package. how do you import it?

**Comment by JLiLab** [comment] 2020-05-24 14:33
I used the reticulate package, as shown in Scanpy in R (https://github.com/theislab/scanpy-in-R)

**Comment by flying-sheep** [comment] 2020-05-25 15:52
Duplicate of #20 or rstudio/reticulate#208 then. I don’t know of a way to properly use reticulate and rpy2 together.

**Comment by flying-sheep** [comment] 2022-07-01 09:14
Fixed in https://github.com/rstudio/reticulate/pull/1188

**Comment by flying-sheep** [comment] 2022-07-01 09:14
Fixed in https://github.com/rstudio/reticulate/pull/1188

**Closed by flying-sheep** 2022-07-01 09:14 UTC
Labels: duplicate
